version: 2

defaults: &defaults
  working_directory: ~/repo
  environment:
    TZ: "Asia/Shanghai"
  docker:
    - image: circleci/node:12

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependences
          command: yarn install
      - run:
          name: Build Package
          command: REACT_APP_BUILD=`date '+%Y%m%d-%H%M%S'` NODE_ENV=production yarn build
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Eslint
          command: yarn lint
      - run:
          name: Unit Test
          command: NODE_ENV=test yarn test --coverage
      - run:
          name: Upload Coverage
          command: bash <(curl -s https://codecov.io/bash)

  release:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker
      - run:
          name: Setup Environment Variables
          command: |
            echo "export TAG=`if test $CIRCLE_TAG; then echo $CIRCLE_TAG; else echo "$CIRCLE_SHA1"; fi`" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Build and Push Image
          command: |
            unset CI
            chmod +x bin/build-docker.sh
            bin/build-docker.sh $TAG $DOCKER_USER $DOCKER_PASS $DOCKER_REGISTRY

  bump:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "15:94:c7:13:68:ce:72:50:04:b0:03:c8:e1:c6:96:f0"
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependences
          command: yarn install
      - run:
          name: git config
          command: |
            git config --global user.email "robot@circleci.com"
            git config --global user.name "robot"
      - run:
          name: bump version
          command: bin/bump.sh

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters: # required since `release` has tag filters AND requires `build`
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters: # required since `release` has tag filters AND requires `test`
            tags:
              only: /.*/
      - release:
          context: production
          requires:
            - test
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
  weekly:
    triggers:
      - schedule:
          cron: "0 23 * * 6"
          filters:
            branches:
              only:
                - master
    jobs:
      - bump
